export const vibeMap = {  
    // Core Fashion Vibes  
    sexy: ["tight", "short", "black", "leather", "form-fitting", "mini", "satin", "deep cut", "slit", "crop", "heels", "mesh", "latex", "corset", "bodycon", "plunging", "strapless", "open-back", "fishnet", "thigh-high"],  
    casual: ["hoodie", "jeans", "sneakers", "cotton", "loose", "graphic", "tshirt", "denim", "flannel", "sweatpants", "slides", "oversized", "dad hat", "cargo", "jersey"],  
    formal: ["blazer", "dress shirt", "suit", "slacks", "oxford", "silk", "wool", "turtleneck", "tuxedo", "pleated", "monochrome", "pencil skirt", "waistcoat", "brooch", "oxford shoes"],  
    sport: ["track", "sweat", "dry-fit", "trainer", "joggers", "polyester", "compression", "windbreaker", "jersey", "cleats", "gym shark", "yoga pants", "high-tops", "headband"],  
    cozy: ["wool", "turtleneck", "fleece", "oversized", "knit", "puffer", "cardigan", "sherpa", "thermal", "cashmere", "blanket scarf", "fuzzy socks", "mukluks", "onesie"],  
    edgy: ["leather", "ripped", "black", "studs", "metal", "chains", "harness", "moto", "grunge", "distressed", "spikes", "goth", "cyberpunk", "latex", "corset"],  
    elegant: ["silk", "lace", "velvet", "gown", "pearl", "chiffon", "sequin", "opera gloves", "tiara", "evening dress", "draped", "high-neck", "mermaid silhouette", "clutch"],  

    // Aesthetic & Subculture Vibes  
    vintage: ["retro", "70s", "80s", "flared", "bell-bottoms", "polka dot", "paisley", "tweed", "victorian", "art deco", "old money"],  
    streetwear: ["hypebeast", "bape", "supreme", "yeezy", "off-white", "camo", "bucket hat", "chunky sneakers", "techwear", "baggy", "logo mania"],  
    bohemian: ["flowy", "maxi", "fringe", "crochet", "kimono", "embroidered", "tassels", "peasant blouse", "wide-brim hat", "ankle boots"],  
    punk: ["safety pins", "tartan", "combat boots", "mohawk", "patches", "band tee", "spiked collar", "DIY", "anarchy"],  
    cottagecore: ["prairie", "puff sleeve", "floral", "lace-up", "apron", "milkmaid", "straw hat", "mushroom print", "pastoral"],  
    y2k: ["frosted tips", "low-rise", "bling", "butterfly clips", "velour", "juicy couture", "bedazzled", "crop top", "denim on denim"],  
    dark_academia: ["tweed", "oxford", "pleated skirt", "wingtips", "trench coat", "beret", "turtleneck", "vintage watch", "leather-bound book"],  
    light_academia: ["beige", "cashmere", "pleated trousers", "loafers", "cardigan", "tortoiseshell glasses", "subtle prints"],  
    cyberpunk: ["neon", "reflective", "techwear", "futuristic", "LED", "visor", "cyber goggles", "holographic", "mech-inspired"],  
    goth: ["lace", "corset", "fishnet", "platforms", "velvet", "choker", "dark lipstick", "cobweb print", "silver jewelry"],  
    kawaii: ["pastel", "frilly", "hello kitty", "puffy sleeves", "knee-high socks", "bows", "plushie accessories", "glitter"],  
    grunge: ["flannel", "combat boots", "ripped stockings", "band tee", "messy hair", "smudged eyeliner", "oversized sweater"],  
    indie_sleaze: ["disheveled", "vintage tee", "skinny jeans", "wayfarers", "fedora", "leather jacket", "cigarette pants"],  
    coastal_grandma: ["linen", "straw bag", "wide-leg pants", "slip-on mules", "pearls", "sunhat", "light blue", "seaglass jewelry"],  
    old_money: ["cable knit", "tweed", "loafers", "pearls", "blazer", "pleated skirt", "monogram", "tennis sweater"],  
    fairy_grunge: ["ethereal", "tattered", "mushroom motifs", "layered skirts", "celestial prints", "dried flowers"],  
    barbiecore: ["hot pink", "sequins", "plastic jewelry", "playful silhouettes", "glitter", "mini dress", "heels"],  
    mermaidcore: ["iridescent", "scales", "seashells", "aqua tones", "flowy fabrics", "pearl embellishments"],  
    angelcore: ["white lace", "feathers", "halo", "sheer fabrics", "glowy makeup", "soft curls", "pearls"],  
    goblincore: ["mossy greens", "mushrooms", "patchwork", "clunky boots", "thrifted layers", "earthy tones"],  
    royalcore: ["regal", "brocade", "crown", "velvet", "ruffles", "jewel tones", "medieval sleeves"],  
    witchy: ["long sleeves", "crescent moon", "crystal jewelry", "layered skirts", "pointy boots", "tarot motifs"],  

    // Mood & Energy Vibes  
    energetic: ["bright colors", "bold prints", "sporty", "neon", "dynamic cuts", "high-shine"],  
    chill: ["oversized", "soft fabrics", "neutral tones", "slouchy", "loungewear", "barefoot"],  
    mysterious: ["deep hues", "layers", "asymmetrical", "veil", "gloves", "smoky makeup"],  
    romantic: ["ruffles", "soft pink", "chiffon", "floral", "pearls", "lace", "heart motifs"],  
    rebellious: ["deconstructed", "graffiti prints", "unfinished hems", "anti-fit", "chaotic layers"],  
    futuristic: ["metallic", "clean lines", "modular", "holographic", "sleek", "armor-like"],  
    nostalgic: ["vintage band tees", "polaroid camera", "mom jeans", "scrunchies", "retro sneakers"],  
    dreamy: ["sheer", "pastel", "sparkle", "feathers", "watercolor prints", "floaty"],  
    powerful: ["sharp tailoring", "structured", "monochrome", "stilettos", "bold shoulders"],  
    soft: ["cashmere", "cloud-like", "feather-light", "muted tones", "round shapes"],  

    // Seasonal Vibes  
    summer: ["linen", "straw hat", "sunglasses", "sandals", "floral", "sundress", "bare shoulders"],  
    winter: ["faux fur", "knit", "thermal", "snow boots", "puffer", "earmuffs", "turtleneck"],  
    autumn: ["plaid", "corduroy", "boots", "scarves", "mustard yellow", "pumpkin spice tones"],  
    spring: ["pastels", "light layers", "floral", "trench coat", "ankle boots", "gauzy fabrics"],  

    // Niche & Hyper-Specific Vibes  
    piratecore: ["ruffled shirt", "bandana", "boots", "earrings", "belted tunic", "tricorn hat"],  
    cowboy: ["denim", "bootcut", "fringe", "hat", "buckle", "western shirt", "leather belt"],  
    detective: ["trench coat", "fedora", "pocket watch", "suspenders", "notebook", "oxfords"],  
    librarian: ["cardigan", "glasses", "pleated skirt", "loafers", "button-up", "messy bun"],  
    rockstar: ["leather pants", "band tee", "aviators", "studs", "messy hair", "mic stand"],  
    vampire: ["velvet", "high collar", "crimson", "pale makeup", "cape", "silver rings"],  
    mafia: ["pinstripe", "fedora", "double-breasted", "wingtips", "cigar", "pocket square"],  
    scifi: ["metallic", "visor", "utility vest", "glow-in-the-dark", "space-age fabrics"],  
    jungle: ["animal print", "safari shirt", "cargo", "hiking boots", "wide-brim hat"],  
    military: ["camo", "combat boots", "cargo pants", "dog tags", "aviator jacket"],  
    skater: ["graphic tee", "vans", "beanie", "cargos", "oversized hoodie", "thrashed look"],  
    balletcore: ["tulle", "ribbon", "satin", "wrap sweater", "pointy flats", "delicate straps"],  
    clowncore: ["color-block", "oversized buttons", "suspenders", "polka dots", "cartoonish"],  
    royalty: ["crown", "ermine", "jewel-encrusted", "velvet robe", "ornate embroidery"],  
    surgeon: ["scrubs", "face mask", "latex gloves", "sterile white", "precision"],  
    astronaut: ["silver", "puffy", "visor", "space boots", "NASA logo", "utility belts"],  
    knight: ["armor", "chainmail", "tabard", "gauntlets", "sword", "medieval"],  
    sailor: ["striped shirt", "nautical", "anchor motifs", "wide-leg pants", "boat shoes"],  
    chef: ["apron", "toque", "checkered pants", "knife roll", "whisk pendant"],  
    raver: ["neon", "fishnet", "kandi", "platforms", "glow sticks", "fuzzy boots"],  
    superhero: ["cape", "spandex", "emblem", "mask", "bold colors", "dynamic"],  
    zombie: ["tattered", "bloodstains", "pale", "grunge", "undead makeup", "chains"],  
    alien: ["iridescent", "unnatural hues", "futuristic", "bug-eyed sunglasses", "otherworldly"],  
};  