// routes/MainComponents/AI/vibePresets.js
const vibePresets = {
    // Original presets
    goth: {
        gender: "any",
        season: "winter",
        occasion: "casual",
        temperature: 10,
        price_range: 100,
        brand: "any",
        color: "black",
        material: "lace",
    },
    cozy: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 5,
        price_range: 70,
        brand: "any",
        color: "beige",
        material: "wool",
    },
    sport: {
        gender: "any",
        season: "summer",
        occasion: "sport",
        temperature: 25,
        price_range: 60,
        brand: "Nike",
        color: "white",
        material: "polyester",
    },

    // New presets
    business: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 20,
        price_range: 200,
        brand: "Hugo Boss",
        color: "navy",
        material: "wool",
    },
    beach: {
        gender: "any",
        season: "summer",
        occasion: "vacation",
        temperature: 30,
        price_range: 50,
        brand: "Billabong",
        color: "blue",
        material: "linen",
    },
    hipster: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 15,
        price_range: 80,
        brand: "Urban Outfitters",
        color: "mustard",
        material: "denim",
    },
    punk: {
        gender: "any",
        season: "all",
        occasion: "concert",
        temperature: 18,
        price_range: 90,
        brand: "any",
        color: "black",
        material: "leather",
    },
    preppy: {
        gender: "any",
        season: "spring",
        occasion: "school",
        temperature: 18,
        price_range: 120,
        brand: "Ralph Lauren",
        color: "pink",
        material: "cotton",
    },
    hiker: {
        gender: "any",
        season: "all",
        occasion: "outdoor",
        temperature: 10,
        price_range: 150,
        brand: "The North Face",
        color: "green",
        material: "nylon",
    },
    rave: {
        gender: "any",
        season: "summer",
        occasion: "party",
        temperature: 22,
        price_range: 70,
        brand: "any",
        color: "neon",
        material: "spandex",
    },
    vintage: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 60,
        brand: "thrift",
        color: "brown",
        material: "tweed",
    },
    yoga: {
        gender: "any",
        season: "all",
        occasion: "fitness",
        temperature: 20,
        price_range: 80,
        brand: "Lululemon",
        color: "purple",
        material: "lycra",
    },
    skater: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 15,
        price_range: 75,
        brand: "Vans",
        color: "gray",
        material: "canvas",
    },
    cowboy: {
        gender: "any",
        season: "summer",
        occasion: "casual",
        temperature: 25,
        price_range: 110,
        brand: "Wrangler",
        color: "denim",
        material: "denim",
    },
    formal: {
        gender: "any",
        season: "all",
        occasion: "formal",
        temperature: 18,
        price_range: 300,
        brand: "Armani",
        color: "black",
        material: "silk",
    },
    boho: {
        gender: "any",
        season: "summer",
        occasion: "festival",
        temperature: 22,
        price_range: 90,
        brand: "Free People",
        color: "patterned",
        material: "crochet",
    },
    military: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 10,
        price_range: 100,
        brand: "any",
        color: "olive",
        material: "canvas",
    },
    fisherman: {
        gender: "any",
        season: "spring",
        occasion: "casual",
        temperature: 12,
        price_range: 85,
        brand: "any",
        color: "orange",
        material: "rubber",
    },
    librarian: {
        gender: "any",
        season: "winter",
        occasion: "work",
        temperature: 15,
        price_range: 95,
        brand: "any",
        color: "burgundy",
        material: "tweed",
    },
    rockstar: {
        gender: "any",
        season: "all",
        occasion: "concert",
        temperature: 18,
        price_range: 200,
        brand: "Saint Laurent",
        color: "black",
        material: "leather",
    },
    surfer: {
        gender: "any",
        season: "summer",
        occasion: "beach",
        temperature: 28,
        price_range: 65,
        brand: "Quiksilver",
        color: "turquoise",
        material: "nylon",
    },
    ski: {
        gender: "any",
        season: "winter",
        occasion: "sport",
        temperature: -5,
        price_range: 250,
        brand: "Columbia",
        color: "red",
        material: "goretex",
    },
    gardener: {
        gender: "any",
        season: "spring",
        occasion: "work",
        temperature: 15,
        price_range: 40,
        brand: "any",
        color: "green",
        material: "cotton",
    },
    chef: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 25,
        price_range: 60,
        brand: "any",
        color: "white",
        material: "polyester",
    },
    detective: {
        gender: "any",
        season: "fall",
        occasion: "work",
        temperature: 10,
        price_range: 120,
        brand: "any",
        color: "tan",
        material: "wool",
    },
    astronaut: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 0,
        price_range: 1000,
        brand: "NASA",
        color: "white",
        material: "nylon",
    },
    pirate: {
        gender: "any",
        season: "summer",
        occasion: "costume",
        temperature: 20,
        price_range: 80,
        brand: "any",
        color: "black",
        material: "satin",
    },
    ninja: {
        gender: "any",
        season: "all",
        occasion: "costume",
        temperature: 15,
        price_range: 70,
        brand: "any",
        color: "black",
        material: "cotton",
    },
    cowboy: {
        gender: "any",
        season: "summer",
        occasion: "casual",
        temperature: 25,
        price_range: 110,
        brand: "Wrangler",
        color: "denim",
        material: "denim",
    },
    welder: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 30,
        price_range: 150,
        brand: "any",
        color: "brown",
        material: "leather",
    },
    sailor: {
        gender: "any",
        season: "summer",
        occasion: "work",
        temperature: 20,
        price_range: 90,
        brand: "any",
        color: "navy",
        material: "cotton",
    },
    firefighter: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 30,
        price_range: 200,
        brand: "any",
        color: "red",
        material: "nylon",
    },
    doctor: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 20,
        price_range: 50,
        brand: "any",
        color: "blue",
        material: "cotton",
    },
    pilot: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 20,
        price_range: 180,
        brand: "any",
        color: "black",
        material: "polyester",
    },
    construction: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 15,
        price_range: 70,
        brand: "Carhartt",
        color: "orange",
        material: "denim",
    },
    fisherman: {
        gender: "any",
        season: "spring",
        occasion: "casual",
        temperature: 12,
        price_range: 85,
        brand: "any",
        color: "orange",
        material: "rubber",
    },
    librarian: {
        gender: "any",
        season: "winter",
        occasion: "work",
        temperature: 15,
        price_range: 95,
        brand: "any",
        color: "burgundy",
        material: "tweed",
    },
    rockstar: {
        gender: "any",
        season: "all",
        occasion: "concert",
        temperature: 18,
        price_range: 200,
        brand: "Saint Laurent",
        color: "black",
        material: "leather",
    },
    surfer: {
        gender: "any",
        season: "summer",
        occasion: "beach",
        temperature: 28,
        price_range: 65,
        brand: "Quiksilver",
        color: "turquoise",
        material: "nylon",
    },
    ski: {
        gender: "any",
        season: "winter",
        occasion: "sport",
        temperature: -5,
        price_range: 250,
        brand: "Columbia",
        color: "red",
        material: "goretex",
    },
    gardener: {
        gender: "any",
        season: "spring",
        occasion: "work",
        temperature: 15,
        price_range: 40,
        brand: "any",
        color: "green",
        material: "cotton",
    },
    chef: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 25,
        price_range: 60,
        brand: "any",
        color: "white",
        material: "polyester",
    },
    detective: {
        gender: "any",
        season: "fall",
        occasion: "work",
        temperature: 10,
        price_range: 120,
        brand: "any",
        color: "tan",
        material: "wool",
    },
    astronaut: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 0,
        price_range: 1000,
        brand: "NASA",
        color: "white",
        material: "nylon",
    },
    pirate: {
        gender: "any",
        season: "summer",
        occasion: "costume",
        temperature: 20,
        price_range: 80,
        brand: "any",
        color: "black",
        material: "satin",
    },
    ninja: {
        gender: "any",
        season: "all",
        occasion: "costume",
        temperature: 15,
        price_range: 70,
        brand: "any",
        color: "black",
        material: "cotton",
    },
    // Seasonal variations
    summerCasual: {
        gender: "any",
        season: "summer",
        occasion: "casual",
        temperature: 28,
        price_range: 50,
        brand: "any",
        color: "white",
        material: "linen",
    },
    winterFormal: {
        gender: "any",
        season: "winter",
        occasion: "formal",
        temperature: 0,
        price_range: 300,
        brand: "any",
        color: "black",
        material: "wool",
    },
    springRomantic: {
        gender: "any",
        season: "spring",
        occasion: "date",
        temperature: 15,
        price_range: 120,
        brand: "any",
        color: "pastel",
        material: "chiffon",
    },
    fallAdventure: {
        gender: "any",
        season: "fall",
        occasion: "outdoor",
        temperature: 10,
        price_range: 150,
        brand: "any",
        color: "brown",
        material: "waxed cotton",
    },
    // More specialized styles
    steampunk: {
        gender: "any",
        season: "fall",
        occasion: "costume",
        temperature: 15,
        price_range: 200,
        brand: "any",
        color: "brown",
        material: "leather",
    },
    cyberpunk: {
        gender: "any",
        season: "all",
        occasion: "costume",
        temperature: 18,
        price_range: 180,
        brand: "any",
        color: "neon",
        material: "vinyl",
    },
    cottagecore: {
        gender: "any",
        season: "spring",
        occasion: "casual",
        temperature: 18,
        price_range: 90,
        brand: "any",
        color: "floral",
        material: "cotton",
    },
    darkAcademia: {
        gender: "any",
        season: "fall",
        occasion: "school",
        temperature: 12,
        price_range: 130,
        brand: "any",
        color: "dark",
        material: "tweed",
    },
    lightAcademia: {
        gender: "any",
        season: "spring",
        occasion: "school",
        temperature: 15,
        price_range: 120,
        brand: "any",
        color: "cream",
        material: "linen",
    },
    // More professional styles
    techCeo: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 20,
        price_range: 150,
        brand: "any",
        color: "gray",
        material: "merino wool",
    },
    creativeDirector: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 18,
        price_range: 200,
        brand: "any",
        color: "black",
        material: "cashmere",
    },
    artist: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 18,
        price_range: 80,
        brand: "any",
        color: "any",
        material: "cotton",
    },
    // More casual styles
    lazySunday: {
        gender: "any",
        season: "all",
        occasion: "home",
        temperature: 20,
        price_range: 40,
        brand: "any",
        color: "gray",
        material: "fleece",
    },
    coffeeShop: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 70,
        brand: "any",
        color: "neutral",
        material: "cotton",
    },
    bookworm: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 60,
        brand: "any",
        color: "earth tones",
        material: "knit",
    },
    // More sporty styles
    runner: {
        gender: "any",
        season: "all",
        occasion: "sport",
        temperature: 15,
        price_range: 100,
        brand: "Adidas",
        color: "bright",
        material: "dri-fit",
    },
    cyclist: {
        gender: "any",
        season: "all",
        occasion: "sport",
        temperature: 15,
        price_range: 150,
        brand: "Rapha",
        color: "black",
        material: "lycra",
    },
    gymRat: {
        gender: "any",
        season: "all",
        occasion: "sport",
        temperature: 20,
        price_range: 80,
        brand: "Under Armour",
        color: "black",
        material: "polyester",
    },
    // More seasonal variations
    rainyDay: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 10,
        price_range: 90,
        brand: "any",
        color: "yellow",
        material: "rubber",
    },
    snowyDay: {
        gender: "any",
        season: "winter",
        occasion: "casual",
        temperature: -10,
        price_range: 120,
        brand: "any",
        color: "red",
        material: "down",
    },
    windyDay: {
        gender: "any",
        season: "spring",
        occasion: "casual",
        temperature: 12,
        price_range: 80,
        brand: "any",
        color: "green",
        material: "windbreaker",
    },
    // More occasion-specific
    firstDate: {
        gender: "any",
        season: "all",
        occasion: "date",
        temperature: 18,
        price_range: 120,
        brand: "any",
        color: "blue",
        material: "silk",
    },
    jobInterview: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 20,
        price_range: 200,
        brand: "any",
        color: "navy",
        material: "wool",
    },
    weddingGuest: {
        gender: "any",
        season: "all",
        occasion: "formal",
        temperature: 20,
        price_range: 180,
        brand: "any",
        color: "pastel",
        material: "satin",
    },
    // More material-focused
    denimLover: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 90,
        brand: "Levi's",
        color: "denim",
        material: "denim",
    },
    leatherLover: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 15,
        price_range: 200,
        brand: "any",
        color: "black",
        material: "leather",
    },
    silkEnthusiast: {
        gender: "any",
        season: "summer",
        occasion: "formal",
        temperature: 22,
        price_range: 150,
        brand: "any",
        color: "any",
        material: "silk",
    },
    // More color-focused
    monochrome: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 100,
        brand: "any",
        color: "black",
        material: "any",
    },
    pastelLover: {
        gender: "any",
        season: "spring",
        occasion: "casual",
        temperature: 18,
        price_range: 90,
        brand: "any",
        color: "pastel",
        material: "cotton",
    },
    neonFiend: {
        gender: "any",
        season: "summer",
        occasion: "party",
        temperature: 25,
        price_range: 70,
        brand: "any",
        color: "neon",
        material: "polyester",
    },
    // More temperature-specific
    heatWave: {
        gender: "any",
        season: "summer",
        occasion: "casual",
        temperature: 35,
        price_range: 50,
        brand: "any",
        color: "white",
        material: "linen",
    },
    freezingCold: {
        gender: "any",
        season: "winter",
        occasion: "casual",
        temperature: -20,
        price_range: 200,
        brand: "any",
        color: "dark",
        material: "down",
    },
    // More price-specific
    budgetFriendly: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 30,
        brand: "any",
        color: "any",
        material: "polyester",
    },
    luxurySeeker: {
        gender: "any",
        season: "all",
        occasion: "formal",
        temperature: 20,
        price_range: 500,
        brand: "Gucci",
        color: "any",
        material: "cashmere",
    },
    // More gender-specific (though most are 'any')
    feminine: {
        gender: "female",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 100,
        brand: "any",
        color: "pink",
        material: "lace",
    },
    masculine: {
        gender: "male",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 100,
        brand: "any",
        color: "blue",
        material: "denim",
    },
    // More brand-focused
    gucciGang: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 500,
        brand: "Gucci",
        color: "any",
        material: "any",
    },
    vintageLevis: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 150,
        brand: "Levi's",
        color: "denim",
        material: "denim",
    },
    // More age-specific
    teenVibe: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 60,
        brand: "Urban Outfitters",
        color: "bright",
        material: "cotton",
    },
    matureStyle: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 150,
        brand: "Brooks Brothers",
        color: "neutral",
        material: "wool",
    },
    // More cultural styles
    parisian: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 200,
        brand: "Chanel",
        color: "black",
        material: "tweed",
    },
    tokyoStreet: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 150,
        brand: "Comme des Garçons",
        color: "black",
        material: "cotton",
    },
    // More fantasy styles
    elf: {
        gender: "any",
        season: "spring",
        occasion: "costume",
        temperature: 15,
        price_range: 120,
        brand: "any",
        color: "green",
        material: "silk",
    },
    wizard: {
        gender: "any",
        season: "winter",
        occasion: "costume",
        temperature: 10,
        price_range: 100,
        brand: "any",
        color: "blue",
        material: "wool",
    },
    // More decade-specific
    eighties: {
        gender: "any",
        season: "all",
        occasion: "party",
        temperature: 18,
        price_range: 80,
        brand: "any",
        color: "bright",
        material: "spandex",
    },
    nineties: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 70,
        brand: "any",
        color: "denim",
        material: "denim",
    },
    // More activity-specific
    camping: {
        gender: "any",
        season: "summer",
        occasion: "outdoor",
        temperature: 15,
        price_range: 120,
        brand: "Patagonia",
        color: "green",
        material: "nylon",
    },
    fishing: {
        gender: "any",
        season: "summer",
        occasion: "outdoor",
        temperature: 20,
        price_range: 100,
        brand: "any",
        color: "khaki",
        material: "cotton",
    },
    // More aesthetic styles
    minimalist: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 120,
        brand: "COS",
        color: "neutral",
        material: "cotton",
    },
    maximalist: {
        gender: "any",
        season: "all",
        occasion: "party",
        temperature: 18,
        price_range: 150,
        brand: "any",
        color: "patterned",
        material: "velvet",
    },
    // More specific professions
    barista: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 20,
        price_range: 60,
        brand: "any",
        color: "black",
        material: "cotton",
    },
    musician: {
        gender: "any",
        season: "all",
        occasion: "concert",
        temperature: 18,
        price_range: 120,
        brand: "any",
        color: "black",
        material: "leather",
    },
    // More specific moods
    rebellious: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 100,
        brand: "any",
        color: "black",
        material: "leather",
    },
    peaceful: {
        gender: "any",
        season: "spring",
        occasion: "casual",
        temperature: 18,
        price_range: 90,
        brand: "any",
        color: "blue",
        material: "linen",
    },
    // More specific patterns
    striped: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 80,
        brand: "any",
        color: "striped",
        material: "cotton",
    },
    plaid: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 15,
        price_range: 90,
        brand: "any",
        color: "plaid",
        material: "flannel",
    },
    // More specific accessories focus
    hatLover: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 100,
        brand: "any",
        color: "any",
        material: "wool",
    },
    scarfEnthusiast: {
        gender: "any",
        season: "winter",
        occasion: "casual",
        temperature: 5,
        price_range: 80,
        brand: "any",
        color: "patterned",
        material: "cashmere",
    },
    // More specific footwear focus
    sneakerhead: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 150,
        brand: "Nike",
        color: "white",
        material: "leather",
    },
    bootLover: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 10,
        price_range: 180,
        brand: "Dr. Martens",
        color: "black",
        material: "leather",
    },
    // More specific garment types
    dressLover: {
        gender: "female",
        season: "summer",
        occasion: "casual",
        temperature: 22,
        price_range: 100,
        brand: "any",
        color: "floral",
        material: "cotton",
    },
    suitEnthusiast: {
        gender: "male",
        season: "all",
        occasion: "work",
        temperature: 18,
        price_range: 250,
        brand: "any",
        color: "navy",
        material: "wool",
    },
    // More specific weather conditions
    humid: {
        gender: "any",
        season: "summer",
        occasion: "casual",
        temperature: 30,
        price_range: 70,
        brand: "any",
        color: "light",
        material: "linen",
    },
    windy: {
        gender: "any",
        season: "spring",
        occasion: "casual",
        temperature: 15,
        price_range: 90,
        brand: "any",
        color: "any",
        material: "windbreaker",
    },
    // More specific body types
    oversized: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 80,
        brand: "any",
        color: "neutral",
        material: "cotton",
    },
    fitted: {
        gender: "any",
        season: "all",
        occasion: "formal",
        temperature: 18,
        price_range: 120,
        brand: "any",
        color: "dark",
        material: "wool",
    },
    // More specific cultural references
    jamesBond: {
        gender: "male",
        season: "all",
        occasion: "formal",
        temperature: 18,
        price_range: 500,
        brand: "Tom Ford",
        color: "black",
        material: "silk",
    },
    marilynMonroe: {
        gender: "female",
        season: "summer",
        occasion: "formal",
        temperature: 22,
        price_range: 200,
        brand: "any",
        color: "white",
        material: "satin",
    },
    // More specific fictional characters
    sherlock: {
        gender: "male",
        season: "fall",
        occasion: "casual",
        temperature: 10,
        price_range: 150,
        brand: "any",
        color: "brown",
        material: "tweed",
    },
    hermione: {
        gender: "female",
        season: "winter",
        occasion: "school",
        temperature: 5,
        price_range: 100,
        brand: "any",
        color: "burgundy",
        material: "wool",
    },cozy: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 5,
        price_range: 70,
        brand: "any",
        color: "beige",
        material: "wool",
    },

    // ========== SUBCULTURE STYLES ==========
    // Gothic Variations
    romanticGoth: {
        gender: "any",
        season: "all",
        occasion: "formal",
        temperature: 15,
        price_range: 150,
        brand: "VampireFreaks",
        color: "burgundy",
        material: "velvet"
    },
    cyberGoth: {
        gender: "any",
        season: "all",
        occasion: "rave",
        temperature: 18,
        price_range: 120,
        brand: "Demobaza",
        color: "neon",
        material: "PVC"
    },
    pastelGoth: {
        gender: "any",
        season: "spring",
        occasion: "casual",
        temperature: 18,
        price_range: 90,
        brand: "Killstar",
        color: "pastel",
        material: "mesh"
    },

    // Punk Variations
    anarchoPunk: {
        gender: "any",
        season: "all",
        occasion: "concert",
        temperature: 15,
        price_range: 50,
        brand: "DIY",
        color: "black",
        material: "denim"
    },
    popPunk: {
        gender: "any",
        season: "all",
        occasion: "concert",
        temperature: 18,
        price_range: 80,
        brand: "Hot Topic",
        color: "checkered",
        material: "cotton"
    },
    crustPunk: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 10,
        price_range: 20,
        brand: "thrift",
        color: "dirty",
        material: "patched"
    },

    // Hipster Variations
    artHipster: {
        gender: "any",
        season: "all",
        occasion: "gallery",
        temperature: 18,
        price_range: 110,
        brand: "Urban Outfitters",
        color: "mustard",
        material: "corduroy"
    },
    coffeeHipster: {
        gender: "any",
        season: "all",
        occasion: "cafe",
        temperature: 18,
        price_range: 95,
        brand: "Everlane",
        color: "neutral",
        material: "organic cotton"
    },
    vintageHipster: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 85,
        brand: "thrift",
        color: "washed",
        material: "denim"
    },

    // Academia Styles
    darkAcademia: {
        gender: "any",
        season: "fall",
        occasion: "school",
        temperature: 12,
        price_range: 130,
        brand: "Ralph Lauren",
        color: "brown",
        material: "tweed"
    },
    lightAcademia: {
        gender: "any",
        season: "spring",
        occasion: "school",
        temperature: 15,
        price_range: 120,
        brand: "J.Crew",
        color: "cream",
        material: "linen"
    },
    chaoticAcademia: {
        gender: "any",
        season: "all",
        occasion: "school",
        temperature: 18,
        price_range: 90,
        brand: "thrift",
        color: "mixed",
        material: "knit"
    },

    // ========== AESTHETIC STYLES ==========
    // Cottagecore Variations
    fairyCottage: {
        gender: "any",
        season: "spring",
        occasion: "picnic",
        temperature: 18,
        price_range: 100,
        brand: "Selkie",
        color: "pastel",
        material: "tulle"
    },
    goblinCore: {
        gender: "any",
        season: "fall",
        occasion: "hiking",
        temperature: 10,
        price_range: 70,
        brand: "thrift",
        color: "mossy",
        material: "wool"
    },
    grandmacore: {
        gender: "any",
        season: "winter",
        occasion: "home",
        temperature: 15,
        price_range: 60,
        brand: "vintage",
        color: "floral",
        material: "quilted"
    },

    // Y2K Variations
    mcbling: {
        gender: "any",
        season: "summer",
        occasion: "party",
        temperature: 22,
        price_range: 80,
        brand: "Juicy Couture",
        color: "pink",
        material: "velour"
    },
    indieSleaze: {
        gender: "any",
        season: "all",
        occasion: "concert",
        temperature: 18,
        price_range: 90,
        brand: "American Apparel",
        color: "black",
        material: "spandex"
    },
    sceneKid: {
        gender: "any",
        season: "all",
        occasion: "mall",
        temperature: 18,
        price_range: 75,
        brand: "Hot Topic",
        color: "neon",
        material: "fishnet"
    },

    // Dark Aesthetics
    vampiric: {
        gender: "any",
        season: "winter",
        occasion: "formal",
        temperature: 10,
        price_range: 200,
        brand: "Alexander McQueen",
        color: "blood red",
        material: "satin"
    },
    witchCore: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 12,
        price_range: 110,
        brand: "Blackcraft",
        color: "purple",
        material: "crochet"
    },
    occult: {
        gender: "any",
        season: "all",
        occasion: "ritual",
        temperature: 15,
        price_range: 150,
        brand: "any",
        color: "black",
        material: "silk"
    },

    // ========== PROFESSIONAL STYLES ==========
    // Corporate
    wallStreet: {
        gender: "male",
        season: "all",
        occasion: "work",
        temperature: 18,
        price_range: 500,
        brand: "Tom Ford",
        color: "navy",
        material: "super 150s wool"
    },
    techCeo: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 20,
        price_range: 150,
        brand: "Theory",
        color: "gray",
        material: "merino wool"
    },
    creativeDirector: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 18,
        price_range: 200,
        brand: "Issey Miyake",
        color: "black",
        material: "pleated fabric"
    },

    // Medical
    surgeon: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 20,
        price_range: 60,
        brand: "Figs",
        color: "blue",
        material: "scrub fabric"
    },
    vintageNurse: {
        gender: "female",
        season: "all",
        occasion: "work",
        temperature: 18,
        price_range: 80,
        brand: "vintage",
        color: "white",
        material: "cotton"
    },
    dentist: {
        gender: "any",
        season: "all",
        occasion: "work",
        temperature: 20,
        price_range: 70,
        brand: "any",
        color: "white",
        material: "polyester"
    },

    // ========== FANTASY/ROLEPLAY ==========
    medieval: {
        gender: "any",
        season: "all",
        occasion: "renaissance fair",
        temperature: 15,
        price_range: 180,
        brand: "Moresca",
        color: "earth tones",
        material: "linen"
    },
    pirate: {
        gender: "any",
        season: "summer",
        occasion: "costume",
        temperature: 20,
        price_range: 120,
        brand: "any",
        color: "black",
        material: "brogue"
    },
    steampunk: {
        gender: "any",
        season: "fall",
        occasion: "convention",
        temperature: 15,
        price_range: 250,
        brand: "Clockwork Couture",
        color: "brown",
        material: "leather"
    },

    // ========== REGIONAL STYLES ==========
    // European
    parisian: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 200,
        brand: "Sézane",
        color: "neutral",
        material: "cashmere"
    },
    scandi: {
        gender: "any",
        season: "winter",
        occasion: "casual",
        temperature: 5,
        price_range: 180,
        brand: "Acne Studios",
        color: "beige",
        material: "wool"
    },
    italianGrandma: {
        gender: "female",
        season: "all",
        occasion: "market",
        temperature: 18,
        price_range: 90,
        brand: "vintage",
        color: "black",
        material: "linen"
    },

    // Asian
    harajuku: {
        gender: "any",
        season: "all",
        occasion: "street",
        temperature: 18,
        price_range: 150,
        brand: "6%DOKIDOKI",
        color: "rainbow",
        material: "tulle"
    },
    kpopIdol: {
        gender: "any",
        season: "all",
        occasion: "performance",
        temperature: 18,
        price_range: 200,
        brand: "We11done",
        color: "designer",
        material: "mixed"
    },
    shaolin: {
        gender: "male",
        season: "all",
        occasion: "training",
        temperature: 15,
        price_range: 80,
        brand: "any",
        color: "brown",
        material: "hemp"
    },

    // ========== SPORTS/ACTIVITIES ==========
    // Winter Sports
    skiBunny: {
        gender: "female",
        season: "winter",
        occasion: "sport",
        temperature: -10,
        price_range: 300,
        brand: "Bogner",
        color: "pink",
        material: "down"
    },
    snowboarder: {
        gender: "any",
        season: "winter",
        occasion: "sport",
        temperature: -5,
        price_range: 250,
        brand: "Burton",
        color: "black",
        material: "goretex"
    },
    iceSkater: {
        gender: "any",
        season: "winter",
        occasion: "sport",
        temperature: 5,
        price_range: 180,
        brand: "Chloe Noel",
        color: "white",
        material: "spandex"
    },

    // ========== MUSIC GENRES ==========
    metalhead: {
        gender: "any",
        season: "all",
        occasion: "concert",
        temperature: 18,
        price_range: 100,
        brand: "band merch",
        color: "black",
        material: "cotton"
    },
    jazzCat: {
        gender: "any",
        season: "all",
        occasion: "club",
        temperature: 18,
        price_range: 150,
        brand: "vintage",
        color: "brown",
        material: "wool"
    },
    raver: {
        gender: "any",
        season: "summer",
        occasion: "festival",
        temperature: 22,
        price_range: 120,
        brand: "iHeartRaves",
        color: "neon",
        material: "spandex"
    },

    // ========== DECADE STYLES ==========
    // 1920s
    flapper: {
        gender: "female",
        season: "all",
        occasion: "party",
        temperature: 18,
        price_range: 180,
        brand: "vintage",
        color: "gold",
        material: "fringe"
    },
    greatGatsby: {
        gender: "male",
        season: "summer",
        occasion: "garden party",
        temperature: 22,
        price_range: 250,
        brand: "Brooks Brothers",
        color: "white",
        material: "linen"
    },

    // 1950s
    pinUp: {
        gender: "female",
        season: "summer",
        occasion: "date",
        temperature: 22,
        price_range: 120,
        brand: "Unique Vintage",
        color: "polka dot",
        material: "cotton"
    },
    greaser: {
        gender: "male",
        season: "all",
        occasion: "diner",
        temperature: 18,
        price_range: 100,
        brand: "Schott",
        color: "black",
        material: "leather"
    },

    // ========== MATERIAL-FOCUSED ==========
    leatherOnly: {
        gender: "any",
        season: "fall",
        occasion: "casual",
        temperature: 15,
        price_range: 300,
        brand: "AllSaints",
        color: "black",
        material: "leather"
    },
    silkEverything: {
        gender: "any",
        season: "summer",
        occasion: "luxury",
        temperature: 22,
        price_range: 400,
        brand: "Silk Maison",
        color: "pastel",
        material: "silk"
    },
    denimOnDenim: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 150,
        brand: "Levi's",
        color: "denim",
        material: "denim"
    },

    // ========== COLOR THEMES ==========
    monochromeBlack: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 120,
        brand: "Rick Owens",
        color: "black",
        material: "any"
    },
    pastelDream: {
        gender: "any",
        season: "spring",
        occasion: "casual",
        temperature: 18,
        price_range: 110,
        brand: "Sandy Liang",
        color: "pastel",
        material: "cotton"
    },
    earthTones: {
        gender: "any",
        season: "fall",
        occasion: "hiking",
        temperature: 12,
        price_range: 100,
        brand: "Patagonia",
        color: "brown/green",
        material: "organic cotton"
    },

    // ========== BODY TYPE SPECIAL ==========
    petiteFashion: {
        gender: "female",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 90,
        brand: "Petite Studio",
        color: "any",
        material: "any"
    },
    tallStyle: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 110,
        brand: "ASOS Tall",
        color: "any",
        material: "any"
    },
    plusSizeChic: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 100,
        brand: "Eloquii",
        color: "any",
        material: "any"
    },

    // ========== SPECIAL OCCASIONS ==========
    weddingGuestSummer: {
        gender: "any",
        season: "summer",
        occasion: "wedding",
        temperature: 25,
        price_range: 180,
        brand: "Reformation",
        color: "floral",
        material: "silk"
    },
    blackTieOptional: {
        gender: "any",
        season: "all",
        occasion: "formal",
        temperature: 18,
        price_range: 300,
        brand: "Gucci",
        color: "black",
        material: "tuxedo"
    },
    beachWedding: {
        gender: "any",
        season: "summer",
        occasion: "wedding",
        temperature: 28,
        price_range: 150,
        brand: "LoveShackFancy",
        color: "white",
        material: "linen"
    },

    // ========== HYBRID STYLES ==========
    gothNinja: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 15,
        price_range: 200,
        brand: "Yohji Yamamoto",
        color: "black",
        material: "technical fabric"
    },
    cowboyPunk: {
        gender: "any",
        season: "summer",
        occasion: "concert",
        temperature: 22,
        price_range: 130,
        brand: "Wrangler",
        color: "black",
        material: "denim/leather"
    },
    preppyGoth: {
        gender: "any",
        season: "fall",
        occasion: "school",
        temperature: 12,
        price_range: 160,
        brand: "Dark Academia",
        color: "black/ivory",
        material: "wool"
    },

    // ========== FUTURISTIC STYLES ==========
    cyberpunk: {
        gender: "any",
        season: "all",
        occasion: "futuristic",
        temperature: 18,
        price_range: 220,
        brand: "Aitor Throup",
        color: "neon",
        material: "tech fabric"
    },
    spaceAge: {
        gender: "any",
        season: "all",
        occasion: "futuristic",
        temperature: 18,
        price_range: 300,
        brand: "Courrèges",
        color: "silver",
        material: "metallic"
    },
    dystopian: {
        gender: "any",
        season: "all",
        occasion: "futuristic",
        temperature: 15,
        price_range: 180,
        brand: "Demobaza",
        color: "gray",
        material: "bonded fabric"
    },

    // ========== CELEBRITY-INSPIRED ==========
    madonna80s: {
        gender: "female",
        season: "all",
        occasion: "concert",
        temperature: 18,
        price_range: 120,
        brand: "vintage",
        color: "lace/denim",
        material: "mixed"
    },
    davidBowie: {
        gender: "male",
        season: "all",
        occasion: "performance",
        temperature: 18,
        price_range: 250,
        brand: "vintage",
        color: "glam",
        material: "velvet"
    },
    rihannaFenty: {
        gender: "female",
        season: "all",
        occasion: "red carpet",
        temperature: 18,
        price_range: 500,
        brand: "Fenty",
        color: "bold",
        material: "luxe"
    },

    // ========== TV/MOVIE INSPIRED ==========
    gossipGirl: {
        gender: "female",
        season: "all",
        occasion: "school",
        temperature: 18,
        price_range: 300,
        brand: "Blair Waldorf",
        color: "preppy",
        material: "tweed"
    },
    peakyBlinders: {
        gender: "male",
        season: "winter",
        occasion: "gangster",
        temperature: 5,
        price_range: 200,
        brand: "vintage",
        color: "gray",
        material: "wool"
    },
    euphoria: {
        gender: "any",
        season: "all",
        occasion: "party",
        temperature: 18,
        price_range: 150,
        brand: "Diesel",
        color: "glitter",
        material: "sequins"
    },

    // ========== UNUSUAL STYLES ==========
    clownCore: {
        gender: "any",
        season: "all",
        occasion: "performance",
        temperature: 18,
        price_range: 90,
        brand: "thrift",
        color: "rainbow",
        material: "polyester"
    },
    cultLeader: {
        gender: "any",
        season: "all",
        occasion: "ritual",
        temperature: 18,
        price_range: 180,
        brand: "Rick Owens",
        color: "black",
        material: "flowing"
    },
    postApocalyptic: {
        gender: "any",
        season: "all",
        occasion: "survival",
        temperature: 15,
        price_range: 130,
        brand: "DIY",
        color: "dirty",
        material: "patched"
    },

    // ========== LUXURY STYLES ==========
    oldMoney: {
        gender: "any",
        season: "all",
        occasion: "yacht",
        temperature: 22,
        price_range: 1000,
        brand: "Loro Piana",
        color: "beige",
        material: "cashmere"
    },
    runwayHighFashion: {
        gender: "any",
        season: "all",
        occasion: "fashion show",
        temperature: 18,
        price_range: 1500,
        brand: "Balenciaga",
        color: "avant-garde",
        material: "experimental"
    },
    quietLuxury: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 800,
        brand: "The Row",
        color: "neutral",
        material: "luxe basics"
    },

    // ========== DIY/ALTERNATIVE ==========
    upcycled: {
        gender: "any",
        season: "all",
        occasion: "casual",
        temperature: 18,
        price_range: 50,
        brand: "DIY",
        color: "patchwork",
        material: "recycled"
    },
    punkDIY: {
        gender: "any",
        season: "all",
        occasion: "concert",
        temperature: 18,
        price_range: 30,
        brand: "DIY",
        color: "anarchy",
        material: "safety pins"
    },
    artStudent: {
        gender: "any",
        season: "all",
        occasion: "studio",
        temperature: 18,
        price_range: 70,
        brand: "thrift",
        color: "paint-splattered",
        material: "canvas"
    },

    // ========== SEASONAL SPECIALS ==========
    holidayUglySweater: {
        gender: "any",
        season: "winter",
        occasion: "party",
        temperature: 5,
        price_range: 60,
        brand: "thrift",
        color: "tacky",
        material: "acrylic"
    },
    summerSolstice: {
        gender: "any",
        season: "summer",
        occasion: "festival",
        temperature: 28,
        price_range: 90,
        brand: "Free People",
        color: "white",
        material: "linen"
    },
    autumnHarvest: {
        gender: "any",
        season: "fall",
        occasion: "thanksgiving",
        temperature: 12,
        price_range: 110,
        brand: "Farm Rio",
        color: "orange",
        material: "corduroy"
    },

    // ========== EXTREME WEATHER ==========
    arcticExplorer: {
        gender: "any",
        season: "winter",
        occasion: "expedition",
        temperature: -30,
        price_range: 400,
        brand: "Canada Goose",
        color: "red",
        material: "down"
    },
    desertNomad: {
        gender: "any",
        season: "summer",
        occasion: "travel",
        temperature: 40,
        price_range: 150,
        brand: "Janne",
        color: "white",
        material: "linen"
    },
    rainforestAdventurer: {
        gender: "any",
        season: "all",
        occasion: "hiking",
        temperature: 25,
        price_range: 180,
        brand: "Fjällräven",
        color: "green",
        material: "G-1000"
    },

};

module.exports = vibePresets;