
export const dummyUsers = [
    {
      userId: 'user1',
      username: 'davidkharrat',
      fullName: 'David Kharrat',
      profilePicture: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      bio: 'Creative developer blending AI + fashion. Coffee lover ☕',
      about: 'Striving to build the future of AI-integrated lifestyle apps.',
      location: 'Beirut, Lebanon',
      followers: 14100,
      following: 1000,
      components: {
        posts: [
            {
              id: 1,
              title: 'Travel Moments',
              items: [
                {
                  id: 'p1',
                  caption: 'Sunset at the beach 🌅',
                  image: '/src/assets/post-sunset.png',
                  timestamp: '2025-04-01T18:00:00Z',
                  likes: 120,
                  comments: 14,
                },
                {
                  id: 'p2',
                  caption: 'Mountain hike adventure 🏔️',
                  image: '/src/assets/post-hike.png',
                  timestamp: '2025-04-02T08:30:00Z',
                  likes: 85,
                  comments: 10,
                },
                {
                  id: 'p3',
                  caption: 'Downtown city lights ✨',
                  image: '/src/assets/post-city.png',
                  timestamp: '2025-04-03T21:00:00Z',
                  likes: 98,
                  comments: 12,
                },
                {
                  id: 'p26',
                  caption: 'Snowy cabin retreat ❄️',
                  image: '/src/assets/post-snow.png',
                  timestamp: '2025-03-15T16:20:00Z',
                  likes: 132,
                  comments: 18,
                },
              ],
            },
            {
              id: 2,
              title: 'Life Updates',
              items: [
                {
                  id: 'p4',
                  caption: 'Working from my favorite café ☕',
                  image: '/src/assets/post-coffee.png',
                  timestamp: '2025-04-04T09:00:00Z',
                  likes: 110,
                  comments: 8,
                },
                {
                  id: 'p5',
                  caption: 'Birthday throwback 🎉',
                  image: '/src/assets/post-birthday.png',
                  timestamp: '2025-04-05T12:00:00Z',
                  likes: 200,
                  comments: 30,
                },
                {
                  id: 'p6',
                  caption: 'Sunday journaling and reflection 📖',
                  image: '/src/assets/post-journal.png',
                  timestamp: '2025-03-30T10:15:00Z',
                  likes: 77,
                  comments: 5,
                },
                {
                  id: 'p7',
                  caption: 'New home, new chapter 🏡',
                  image: '/src/assets/post-home.png',
                  timestamp: '2025-03-25T14:45:00Z',
                  likes: 184,
                  comments: 22,
                },
              ],
            },
            {
              id: 3,
              title: 'Style & Fits',
              items: [
                {
                  id: 'p8',
                  caption: 'Today’s outfit: street-ready 🖤',
                  image: '/src/assets/post-fit1.png',
                  timestamp: '2025-03-29T12:00:00Z',
                  likes: 168,
                  comments: 24,
                },
                {
                  id: 'p9',
                  caption: 'Clean and minimal vibes ⚪️',
                  image: '/src/assets/post-fit2.png',
                  timestamp: '2025-03-28T09:10:00Z',
                  likes: 145,
                  comments: 15,
                },
                {
                  id: 'p10',
                  caption: 'Layering for the win 🧥',
                  image: '/src/assets/post-layered.png',
                  timestamp: '2025-03-26T17:00:00Z',
                  likes: 173,
                  comments: 20,
                },
              ],
            },
            {
              id: 4,
              title: 'Food Diary',
              items: [
                {
                  id: 'p11',
                  caption: 'Avocado toast done right 🥑🍞',
                  image: '/src/assets/post-avocado.png',
                  timestamp: '2025-03-20T08:30:00Z',
                  likes: 112,
                  comments: 9,
                },
                {
                  id: 'p12',
                  caption: 'Post-workout smoothie bowl 💪🍓',
                  image: '/src/assets/post-smoothie.png',
                  timestamp: '2025-03-21T11:15:00Z',
                  likes: 89,
                  comments: 7,
                },
                {
                  id: 'p13',
                  caption: 'Cozy dinner with a view 🍷',
                  image: '/src/assets/post-dinner.png',
                  timestamp: '2025-03-22T20:00:00Z',
                  likes: 142,
                  comments: 13,
                },
              ],
            },
            {
              id: 5,
              title: 'Behind the Scenes',
              items: [
                {
                  id: 'p14',
                  caption: 'Studio setup for AI fashion shoot 🎬',
                  image: '/src/assets/post-studio.png',
                  timestamp: '2025-03-18T15:45:00Z',
                  likes: 210,
                  comments: 34,
                },
                {
                  id: 'p15',
                  caption: 'Debugging late into the night 🧠💻',
                  image: '/src/assets/post-debug.png',
                  timestamp: '2025-03-17T22:10:00Z',
                  likes: 156,
                  comments: 19,
                },
              ],
            },
            {
              id: 6,
              title: 'Nature Escapes',
              items: [
                {
                  id: 'p16',
                  caption: 'Spring blooms are here 🌸',
                  image: '/src/assets/post-flowers.png',
                  timestamp: '2025-03-12T11:00:00Z',
                  likes: 98,
                  comments: 11,
                },
                {
                  id: 'p17',
                  caption: 'River walk meditation 🌊',
                  image: '/src/assets/post-river.png',
                  timestamp: '2025-03-10T07:45:00Z',
                  likes: 120,
                  comments: 9,
                },
              ],
            },
            {
              id: 7,
              title: 'Fitness Journey',
              items: [
                {
                  id: 'p18',
                  caption: 'Leg day grind 🦵🔥',
                  image: '/src/assets/post-gym1.png',
                  timestamp: '2025-03-08T18:00:00Z',
                  likes: 130,
                  comments: 12,
                },
                {
                  id: 'p19',
                  caption: 'Hitting a new PR today! 🏋️‍♂️',
                  image: '/src/assets/post-pr.png',
                  timestamp: '2025-03-05T17:30:00Z',
                  likes: 165,
                  comments: 17,
                },
                {
                  id: 'p20',
                  caption: 'Post-cardio peace ☮️',
                  image: '/src/assets/post-cardio.png',
                  timestamp: '2025-03-06T08:15:00Z',
                  likes: 98,
                  comments: 6,
                },
              ],
            },
          ],
        wardrobe: [
            {
                id: 2,
                title: 'Hats',
                items: [
                  {
                    id: 'h1',
                    itemName: 'Classic Baseball Cap',
                    category: 'hats',
                    color: 'black',
                    brand: 'New Era',
                    material: 'cotton',
                    season: 'all',
                    image: 'https://cdn.shopify.com/s/files/1/0094/2252/products/NewEra_9FIFTY_Black_1200x1200.jpg?v=1613166921',
                    gender: 'unisex',
                    occasion: 'casual',
                    price: 35,
                    type: 'baseball cap',
                    temperature_range: [15, 30],
                    essential: true,
                  },
                  {
                    id: 'h2',
                    itemName: 'Wool Beanie',
                    category: 'hats',
                    color: 'gray',
                    brand: 'Carhartt',
                    material: 'wool',
                    season: 'winter',
                    image: 'https://m.media-amazon.com/images/I/71vCu+S3VBL._AC_UX679_.jpg',
                    gender: 'unisex',
                    occasion: 'casual',
                    price: 25,
                    type: 'beanie',
                    temperature_range: [-10, 15],
                    essential: true,
                  },
                  {
                    id: 'h3',
                    itemName: 'Panama Hat',
                    category: 'hats',
                    color: 'natural',
                    brand: 'Brixton',
                    material: 'straw',
                    season: 'summer',
                    image: 'https://images.asos-media.com/products/brixton-panama-hat-in-natural/202326818-1-natural?$n_640w$&wid=513&fit=constrain',
                    gender: 'unisex',
                    occasion: 'summer',
                    price: 65,
                    type: 'sun hat',
                    temperature_range: [20, 40],
                    essential: false,
                  },
                  {
                    id: 'h4',
                    itemName: 'Fedora',
                    category: 'hats',
                    color: 'brown',
                    brand: 'Stetson',
                    material: 'wool felt',
                    season: 'fall',
                    image: 'https://www.stetson.com/dw/image/v2/AAVW_PRD/on/demandware.static/-/Sites-master-catalog-stetson/default/dw1f1c5a1d/images/large/10142000_10142000_1.jpg?sw=800&sh=800',
                    gender: 'unisex',
                    occasion: 'semi-formal',
                    price: 120,
                    type: 'fedora',
                    temperature_range: [5, 25],
                    essential: false,
                  },
                  {
                    id: 'h5',
                    itemName: 'Bucket Hat',
                    category: 'hats',
                    color: 'khaki',
                    brand: 'Nike',
                    material: 'nylon',
                    season: 'summer',
                    image: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/3a1a8b3a-0e8a-4d7b-9b3a-3e3a3a3a3a3a/sportswear-bucket-hat-3JZ7QZ.png',
                    gender: 'unisex',
                    occasion: 'casual',
                    price: 30,
                    type: 'bucket hat',
                    temperature_range: [20, 35],
                    essential: false,
                  },
                  {
                    id: 'h6',
                    itemName: 'Newsboy Cap',
                    category: 'hats',
                    color: 'navy',
                    brand: 'Bailey of Hollywood',
                    material: 'wool',
                    season: 'fall',
                    image: 'https://www.baileyhats.com/dw/image/v2/AAVW_PRD/on/demandware.static/-/Sites-master-catalog-bailey/default/dw3b3b3b3b/images/large/10142000_10142000_1.jpg?sw=800&sh=800',
                    gender: 'unisex',
                    occasion: 'smart casual',
                    price: 85,
                    type: 'flat cap',
                    temperature_range: [5, 20],
                    essential: false,
                  },
                  {
                    id: 'h7',
                    itemName: 'Winter Trapper Hat',
                    category: 'hats',
                    color: 'black',
                    brand: 'The North Face',
                    material: 'nylon/fleece',
                    season: 'winter',
                    image: 'https://images.thenorthface.com/is/image/TheNorthFace/NF0A3R5S_001_hero?$638x745$',
                    gender: 'unisex',
                    occasion: 'outdoor',
                    price: 75,
                    type: 'trapper hat',
                    temperature_range: [-20, 10],
                    essential: true,
                  },
                  {
                    id: 'h8',
                    itemName: 'Straw Cowboy Hat',
                    category: 'hats',
                    color: 'tan',
                    brand: 'Resistol',
                    material: 'straw',
                    season: 'summer',
                    image: 'https://www.resistol.com/dw/image/v2/AAVW_PRD/on/demandware.static/-/Sites-master-catalog-resistol/default/dw1f1c5a1d/images/large/10142000_10142000_1.jpg?sw=800&sh=800',
                    gender: 'unisex',
                    occasion: 'western',
                    price: 90,
                    type: 'cowboy hat',
                    temperature_range: [20, 40],
                    essential: false,
                  },
                  {
                    id: 'h9',
                    itemName: 'Trucker Hat',
                    category: 'hats',
                    color: 'denim',
                    brand: 'Carhartt',
                    material: 'cotton/mesh',
                    season: 'all',
                    image: 'https://m.media-amazon.com/images/I/71vCu+S3VBL._AC_UX679_.jpg',
                    gender: 'unisex',
                    occasion: 'casual',
                    price: 22,
                    type: 'trucker cap',
                    temperature_range: [10, 30],
                    essential: false,
                  },
                  {
                    id: 'h10',
                    itemName: 'Wide Brim Sun Hat',
                    category: 'hats',
                    color: 'white',
                    brand: 'Eugenia Kim',
                    material: 'straw',
                    season: 'summer',
                    image: 'https://www.eugeniakim.com/dw/image/v2/AAVW_PRD/on/demandware.static/-/Sites-master-catalog-eugeniakim/default/dw1f1c5a1d/images/large/10142000_10142000_1.jpg?sw=800&sh=800',
                    gender: 'female',
                    occasion: 'beach',
                    price: 150,
                    type: 'sun hat',
                    temperature_range: [25, 40],
                    essential: false,
                  },
                  {
                    id: 'h11',
                    itemName: 'Beret',
                    category: 'hats',
                    color: 'red',
                    brand: 'Laulhère',
                    material: 'wool',
                    season: 'fall',
                    image: 'https://www.laulhere-france.com/dw/image/v2/AAVW_PRD/on/demandware.static/-/Sites-master-catalog-laulhere/default/dw1f1c5a1d/images/large/10142000_10142000_1.jpg?sw=800&sh=800',
                    gender: 'unisex',
                    occasion: 'fashion',
                    price: 65,
                    type: 'beret',
                    temperature_range: [5, 20],
                    essential: false,
                  },
                  {
                    id: 'h12',
                    itemName: 'Military Cap',
                    category: 'hats',
                    color: 'olive',
                    brand: 'Alpha Industries',
                    material: 'cotton',
                    season: 'all',
                    image: 'https://www.alphaindustries.com/dw/image/v2/AAVW_PRD/on/demandware.static/-/Sites-master-catalog-alpha/default/dw1f1c5a1d/images/large/10142000_10142000_1.jpg?sw=800&sh=800',
                    gender: 'unisex',
                    occasion: 'casual',
                    price: 28,
                    type: 'military cap',
                    temperature_range: [10, 25],
                    essential: false,
                  },
                  {
                    id: 'h13',
                    itemName: 'Fleece Beanie',
                    category: 'hats',
                    color: 'charcoal',
                    brand: 'Patagonia',
                    material: 'recycled fleece',
                    season: 'winter',
                    image: 'https://www.patagonia.com/dw/image/v2/BDJB_PRD/on/demandware.static/-/Sites-master-catalog-patagonia/default/dw1f1c5a1d/images/large/10142000_10142000_1.jpg?sw=800&sh=800',
                    gender: 'unisex',
                    occasion: 'outdoor',
                    price: 35,
                    type: 'beanie',
                    temperature_range: [-15, 10],
                    essential: true,
                  },
                  {
                    id: 'h14',
                    itemName: 'Golf Visor',
                    category: 'hats',
                    color: 'white',
                    brand: 'Nike',
                    material: 'polyester',
                    season: 'summer',
                    image: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/3a1a8b3a-0e8a-4d7b-9b3a-3e3a3a3a3a3a/sportswear-golf-visor-3JZ7QZ.png',
                    gender: 'unisex',
                    occasion: 'sports',
                    price: 25,
                    type: 'visor',
                    temperature_range: [20, 35],
                    essential: false,
                  },
                  {
                    id: 'h15',
                    itemName: 'Leather Baseball Cap',
                    category: 'hats',
                    color: 'brown',
                    brand: 'Gucci',
                    material: 'leather',
                    season: 'all',
                    image: 'https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1679325946/686749_XKX40_1000_001_100_0000_Light-Gucci-Leather-baseball-cap.jpg',
                    gender: 'unisex',
                    occasion: 'luxury casual',
                    price: 450,
                    type: 'baseball cap',
                    temperature_range: [10, 25],
                    essential: false,
                  }
                ]
              },
                {
                  id: 1,
                  title: 'Shoes',
                  items: [
                    {
                      id: 'w1',
                      itemName: 'White Sneakers',
                      category: 'shoes',
                      color: 'white',
                      brand: 'Nike',
                      material: 'leather',
                      season: 'all',
                      image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4f37fca8-6bce-43e7-ad07-f57ae3c13142/AIR+FORCE+1+%2707.png',
                      gender: 'male',
                      occasion: 'casual',
                      price: 100,
                      type: 'sneakers',
                      temperature_range: [10, 30],
                      essential: true,
                    },
                    {
                      id: 'w2',
                      itemName: 'Black Chelsea Boots',
                      category: 'shoes',
                      color: 'black',
                      brand: 'Zara',
                      material: 'suede',
                      season: 'fall',
                      image: 'https://static.zara.net/assets/public/336f/e3e1/f78d4d2ea83b/74e22883ccb9/12001422800-e1/12001422800-e1.jpg?ts=1722336077343&w=440',
                      gender: 'male',
                      occasion: 'formal',
                      price: 110,
                      type: 'boots',
                      temperature_range: [5, 20],
                      essential: true,
                    },
                    {
                      id: 'w3',
                      itemName: 'Running Shoes',
                      category: 'shoes',
                      color: 'blue',
                      brand: 'Adidas',
                      material: 'mesh',
                      season: 'spring',
                      image: 'https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/fcb3638c2dc54675b45244447918db99_9366/adizero-boston-12-shoes.jpg',
                      gender: 'male',
                      occasion: 'sports',
                      price: 85,
                      type: 'sneakers',
                      temperature_range: [10, 25],
                      essential: false,
                    },
                    {
                      id: 'w4',
                      itemName: 'High-top Converse',
                      category: 'shoes',
                      color: 'red',
                      brand: 'Converse',
                      material: 'canvas',
                      season: 'summer',
                      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLtJPV224N3l8vr2h9rlBPTchp1RAsfI4-fg&s',
                      gender: 'male',
                      occasion: 'casual',
                      price: 75,
                      type: 'sneakers',
                      temperature_range: [15, 30],
                      essential: false,
                    },
                    {
                      id: 'w5',
                      itemName: 'Leather Loafers',
                      category: 'shoes',
                      color: 'brown',
                      brand: 'Clarks',
                      material: 'leather',
                      season: 'spring',
                      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2nY1F66EoXjdFd6TnEzjHfQ7pb7X4_JM-mQ&s',
                      gender: 'male',
                      occasion: 'formal',
                      price: 95,
                      type: 'loafers',
                      temperature_range: [10, 25],
                      essential: true,
                    },
                  ],
                },
                {
                  id: 2,
                  title: 'Tops',
                  items: [
                    {
                      id: 'w6',
                      itemName: 'Black Hoodie',
                      category: 'top',
                      color: 'black',
                      brand: 'H&M',
                      material: 'cotton',
                      season: 'winter',
                      image: 'https://hourscollection.com/cdn/shop/files/DropShoulderHoodie-Black-product_800x.jpg?v=1739921675',
                      gender: 'male',
                      occasion: 'casual',
                      price: 60,
                      type: 'hoodie',
                      temperature_range: [0, 15],
                      essential: true,
                    },
                    {
                      id: 'w7',
                      itemName: 'Pastel Pink Hoodie',
                      category: 'top',
                      color: 'pink',
                      brand: 'Uniqlo',
                      material: 'fleece',
                      season: 'spring',
                      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT09rP1QlEuablllAPN3ca9uzhDjD2qj1nfqA&s',
                      gender: 'male',
                      occasion: 'casual',
                      price: 55,
                      type: 'hoodie',
                      temperature_range: [10, 20],
                      essential: false,
                    },
                    {
                      id: 'w8',
                      itemName: 'White Linen Shirt',
                      category: 'top',
                      color: 'white',
                      brand: 'Zara',
                      material: 'linen',
                      season: 'summer',
                      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOOBoJBf5MC6tx0kKLGNSw8HytgWBToQAvMQ&s',
                      gender: 'male',
                      occasion: 'formal',
                      price: 65,
                      type: 'shirt',
                      temperature_range: [20, 35],
                      essential: true,
                    },
                    {
                      id: 'w9',
                      itemName: 'Grey Graphic Tee',
                      category: 'top',
                      color: 'gray',
                      brand: 'Bershka',
                      material: 'cotton',
                      season: 'summer',
                      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgPGK2pco52GqNX-1LNH_mChpvRQBY9o-S2A&s',
                      gender: 'male',
                      occasion: 'casual',
                      price: 30,
                      type: 't-shirt',
                      temperature_range: [20, 35],
                      essential: true,
                    },
                    {
                      id: 'w10',
                      itemName: 'Turtleneck Sweater',
                      category: 'top',
                      color: 'beige',
                      brand: 'Mango',
                      material: 'wool',
                      season: 'winter',
                      image: 'https://cdn-images.farfetch-contents.com/25/16/29/48/25162948_55416746_600.jpg',
                      gender: 'male',
                      occasion: 'formal',
                      price: 80,
                      type: 'sweater',
                      temperature_range: [-5, 10],
                      essential: true,
                    },
                  ],
                },
                {
                    id: 3,
                    title: 'Accessories',
                    items: [
                      {
                        id: 'a1',
                        itemName: 'Classic Aviator Sunglasses',
                        category: 'accessories',
                        color: 'gold',
                        brand: 'Ray-Ban',
                        material: 'metal/glass',
                        season: 'all',
                        image: '',
                        gender: 'unisex',
                        occasion: 'casual',
                        price: 153,
                        type: 'sunglasses',
                        temperature_range: [10, 40],
                        essential: true,
                      },
                      {
                        id: 'a2',
                        itemName: 'Leather Belt',
                        category: 'accessories',
                        color: 'brown',
                        brand: 'Allen Edmonds',
                        material: 'leather',
                        season: 'all',
                        image: '',
                        gender: 'unisex',
                        occasion: 'formal',
                        price: 89,
                        type: 'belt',
                        temperature_range: [0, 35],
                        essential: true,
                      },
                      {
                        id: 'a3',
                        itemName: 'Silk Scarf',
                        category: 'accessories',
                        color: 'multicolor',
                        brand: 'Hermès',
                        material: 'silk',
                        season: 'fall',
                        image: '',
                        gender: 'female',
                        occasion: 'formal',
                        price: 375,
                        type: 'scarf',
                        temperature_range: [5, 25],
                        essential: false,
                      },
                      {
                        id: 'a4',
                        itemName: 'Leather Gloves',
                        category: 'accessories',
                        color: 'black',
                        brand: 'Coach',
                        material: 'leather',
                        season: 'winter',
                        image: '',
                        gender: 'unisex',
                        occasion: 'formal',
                        price: 98,
                        type: 'gloves',
                        temperature_range: [-10, 15],
                        essential: true,
                      },
                      {
                        id: 'a5',
                        itemName: 'Canvas Tote Bag',
                        category: 'accessories',
                        color: 'beige',
                        brand: 'LL Bean',
                        material: 'canvas',
                        season: 'all',
                        image: '',
                        gender: 'unisex',
                        occasion: 'casual',
                        price: 35,
                        type: 'bag',
                        temperature_range: [10, 35],
                        essential: false,
                      },
                      {
                        id: 'a6',
                        itemName: 'Stainless Steel Watch',
                        category: 'accessories',
                        color: 'silver',
                        brand: 'Timex',
                        material: 'stainless steel',
                        season: 'all',
                        image: '',
                        gender: 'unisex',
                        occasion: 'formal',
                        price: 129,
                        type: 'watch',
                        temperature_range: [0, 40],
                        essential: true,
                      },
                      {
                        id: 'a7',
                        itemName: 'Cashmere Wrap',
                        category: 'accessories',
                        color: 'charcoal',
                        brand: 'Nordstrom',
                        material: 'cashmere',
                        season: 'winter',
                        image: '',
                        gender: 'female',
                        occasion: 'formal',
                        price: 149,
                        type: 'shawl',
                        temperature_range: [-5, 20],
                        essential: false,
                      },
                      {
                        id: 'a8',
                        itemName: 'Cotton Bandana',
                        category: 'accessories',
                        color: 'red',
                        brand: 'Bandana Republic',
                        material: 'cotton',
                        season: 'summer',
                        image: '',
                        gender: 'unisex',
                        occasion: 'casual',
                        price: 12,
                        type: 'bandana',
                        temperature_range: [15, 40],
                        essential: false,
                      },
                      {
                        id: 'a9',
                        itemName: 'Leather Wallet',
                        category: 'accessories',
                        color: 'black',
                        brand: 'Fossil',
                        material: 'leather',
                        season: 'all',
                        image: '',
                        gender: 'male',
                        occasion: 'casual',
                        price: 55,
                        type: 'wallet',
                        temperature_range: [0, 40],
                        essential: true,
                      },
                      {
                        id: 'a10',
                        itemName: 'Statement Necklace',
                        category: 'accessories',
                        color: 'gold',
                        brand: 'Kendra Scott',
                        material: 'metal',
                        season: 'all',
                        image: '',
                        gender: 'female',
                        occasion: 'formal',
                        price: 85,
                        type: 'jewelry',
                        temperature_range: [10, 30],
                        essential: false,
                      },
                      {
                        id: 'a11',
                        itemName: 'Canvas Belt',
                        category: 'accessories',
                        color: 'khaki',
                        brand: 'Dickies',
                        material: 'canvas',
                        season: 'summer',
                        image: '',
                        gender: 'unisex',
                        occasion: 'casual',
                        price: 22,
                        type: 'belt',
                        temperature_range: [15, 40],
                        essential: false,
                      },
                      {
                        id: 'a12',
                        itemName: 'Silk Pocket Square',
                        category: 'accessories',
                        color: 'navy',
                        brand: 'Brooks Brothers',
                        material: 'silk',
                        season: 'all',
                        image: '',
                        gender: 'male',
                        occasion: 'formal',
                        price: 45,
                        type: 'pocket square',
                        temperature_range: [0, 35],
                        essential: false,
                      },
                      {
                        id: 'a13',
                        itemName: 'Wool Beanie',
                        category: 'accessories',
                        color: 'gray',
                        brand: 'Carhartt',
                        material: 'wool',
                        season: 'winter',
                        image: '',
                        gender: 'unisex',
                        occasion: 'casual',
                        price: 25,
                        type: 'hat',
                        temperature_range: [-10, 15],
                        essential: true,
                      },
                      {
                        id: 'a14',
                        itemName: 'Titanium Ring',
                        category: 'accessories',
                        color: 'silver',
                        brand: 'QALO',
                        material: 'titanium',
                        season: 'all',
                        image: '',
                        gender: 'unisex',
                        occasion: 'casual',
                        price: 65,
                        type: 'jewelry',
                        temperature_range: [-20, 50],
                        essential: false,
                      },
                      {
                        id: 'a15',
                        itemName: 'Nylon Backpack',
                        category: 'accessories',
                        color: 'black',
                        brand: 'JanSport',
                        material: 'nylon',
                        season: 'all',
                        image: '',
                        gender: 'unisex',
                        occasion: 'casual',
                        price: 45,
                        type: 'bag',
                        temperature_range: [-10, 40],
                        essential: true,
                      }
                    ]
                  },
                
              
                {
                    id: 3,
                    title: 'Bottoms',
                    items: [
                      {
                        id: 'w11',
                        itemName: 'Slim Fit Pants',
                        category: 'bottom',
                        color: 'gray',
                        brand: 'Zara',
                        material: 'cotton',
                        season: 'all',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9EskwQ5a0-r6ElZPDH8tb6upO3fw3GkUPuQ&s',
                        gender: 'male',
                        occasion: 'formal',
                        price: 70,
                        type: 'pants',
                        temperature_range: [10, 25],
                        essential: true,
                      },
                      {
                        id: 'w12',
                        itemName: 'Joggers',
                        category: 'bottom',
                        color: 'navy',
                        brand: 'Nike',
                        material: 'polyester',
                        season: 'fall',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDjUn6fwio3wiG8IxQT1Krrz6_imKr4i6pfg&s',
                        gender: 'male',
                        occasion: 'sports',
                        price: 50,
                        type: 'joggers',
                        temperature_range: [8, 20],
                        essential: false,
                      },
                      {
                        id: 'w13',
                        itemName: 'Light Blue Jeans',
                        category: 'bottom',
                        color: 'light blue',
                        brand: 'Levi’s',
                        material: 'denim',
                        season: 'spring',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQRuXTvjGWdkPZjRS14Bvqq57rgoGCZEBBrQ&s',
                        gender: 'male',
                        occasion: 'casual',
                        price: 85,
                        type: 'jeans',
                        temperature_range: [12, 25],
                        essential: true,
                      },
                      {
                        id: 'w14',
                        itemName: 'Beige Chinos',
                        category: 'bottom',
                        color: 'beige',
                        brand: 'H&M',
                        material: 'cotton',
                        season: 'summer',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2qrZyAQtj3seZlPiLRxIvvTjMqMfyRAcQ1g&s',
                        gender: 'male',
                        occasion: 'formal',
                        price: 60,
                        type: 'chinos',
                        temperature_range: [18, 32],
                        essential: true,
                      },
                      {
                        id: 'w15',
                        itemName: 'Black Cargo Pants',
                        category: 'bottom',
                        color: 'black',
                        brand: 'Pull&Bear',
                        material: 'polyester',
                        season: 'winter',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReFiMdrYDtJj14t3SvNX-Mbpws51AGHfG9IA&s',
                        gender: 'male',
                        occasion: 'casual',
                        price: 75,
                        type: 'cargo',
                        temperature_range: [0, 15],
                        essential: false,
                      },
                    ],
                  },
                  
                  {
                    id: 4,
                    title: 'Jackets',
                    items: [
                      {
                        id: 'w16',
                        itemName: 'Denim Jacket',
                        category: 'outerwear',
                        color: 'blue',
                        brand: 'Levi’s',
                        material: 'denim',
                        season: 'fall',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7Bt4xIgTnryoiqgw7b7kLc4BDQ26D1uyd4g&s',
                        gender: 'male',
                        occasion: 'casual',
                        price: 90,
                        type: 'jacket',
                        temperature_range: [10, 20],
                        essential: true,
                      },
                      {
                        id: 'w17',
                        itemName: 'Puffer Jacket',
                        category: 'outerwear',
                        color: 'green',
                        brand: 'North Face',
                        material: 'nylon',
                        season: 'winter',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRziollxyq0N4rECJJkY7NF4R5KLiMaz8O3eg&s',
                        gender: 'male',
                        occasion: 'outdoor',
                        price: 130,
                        type: 'jacket',
                        temperature_range: [-10, 10],
                        essential: true,
                      },
                      {
                        id: 'w18',
                        itemName: 'Blazer',
                        category: 'outerwear',
                        color: 'navy',
                        brand: 'Massimo Dutti',
                        material: 'wool',
                        season: 'fall',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1NOdKQ0GwXTL4JFHrBX6IgVucEk8GXP751A&s',
                        gender: 'male',
                        occasion: 'formal',
                        price: 150,
                        type: 'blazer',
                        temperature_range: [10, 18],
                        essential: true,
                      },
                      {
                        id: 'w19',
                        itemName: 'Raincoat',
                        category: 'outerwear',
                        color: 'yellow',
                        brand: 'Uniqlo',
                        material: 'polyester',
                        season: 'spring',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBvytNMkbrgpATh_OLhBObyxCEuWMfQx3D1Q&s',
                        gender: 'male',
                        occasion: 'outdoor',
                        price: 80,
                        type: 'raincoat',
                        temperature_range: [10, 25],
                        essential: false,
                      },
                      {
                        id: 'w20',
                        itemName: 'blackcoat',
                        category: 'outerwear',
                        color: 'black',
                        brand: 'Uniqlo',
                        material: 'polyester',
                        season: 'spring',
                        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFD7_ZgNRkDasJmmCbK3aHSa9SpfGtUKkJFg&s',
                        gender: 'male',
                        occasion: 'outdoor',
                        price: 80,
                        type: 'raincoat',
                        temperature_range: [10, 25],
                        essential: false,
                      }
                    ],
                  },
        ],
  
        outfits: [
            {
              id: 1,
              title: 'Casual Friday',
              wardrobeItems: ['w9', 'w13', 'w1'],
              items: [
                { id: 'w9', itemName: 'Grey Graphic Tee', image: '/src/assets/tee-graphic.png' },
                { id: 'w13', itemName: 'Light Blue Jeans', image: '/src/assets/jeans-lightblue.png' },
                { id: 'w1', itemName: 'White Sneakers', image: '/src/assets/shoes-white.png' },
              ],
            },
            {
              id: 2,
              title: 'Date Night',
              wardrobeItems: ['w10', 'w11', 'w2'],
              items: [
                { id: 'w10', itemName: 'Turtleneck Sweater', image: '/src/assets/turtleneck.png' },
                { id: 'w11', itemName: 'Slim Fit Pants', image: '/src/assets/pants-slim.png' },
                { id: 'w2', itemName: 'Black Chelsea Boots', image: '/src/assets/shoes-boots.png' },
              ],
            },
            {
              id: 3,
              title: 'Gym Fit',
              wardrobeItems: ['w9', 'w12', 'w3'],
              items: [
                { id: 'w9', itemName: 'Grey Graphic Tee', image: '/src/assets/tee-graphic.png' },
                { id: 'w12', itemName: 'Joggers', image: '/src/assets/joggers-navy.png' },
                { id: 'w3', itemName: 'Running Shoes', image: '/src/assets/shoes-run.png' },
              ],
            },
            {
              id: 4,
              title: 'Autumn Streets',
              wardrobeItems: ['w15', 'w6', 'w16'],
              items: [
                { id: 'w15', itemName: 'Black Cargo Pants', image: '/src/assets/cargo-black.png' },
                { id: 'w6', itemName: 'Black Hoodie', image: '/src/assets/hoodie-black.png' },
                { id: 'w16', itemName: 'Denim Jacket', image: '/src/assets/jacket-denim.png' },
              ],
            },
            {
              id: 5,
              title: 'Spring Stroll',
              wardrobeItems: ['w8', 'w14', 'w4'],
              items: [
                { id: 'w8', itemName: 'White Linen Shirt', image: '/src/assets/shirt-linen.png' },
                { id: 'w14', itemName: 'Beige Chinos', image: '/src/assets/chinos-beige.png' },
                { id: 'w4', itemName: 'High-top Converse', image: '/src/assets/shoes-converse.png' },
              ],
            },
            {
              id: 6,
              title: 'Business Casual',
              wardrobeItems: ['w10', 'w14', 'w18'],
              items: [
                { id: 'w10', itemName: 'Turtleneck Sweater', image: '/src/assets/turtleneck.png' },
                { id: 'w14', itemName: 'Beige Chinos', image: '/src/assets/chinos-beige.png' },
                { id: 'w18', itemName: 'Blazer', image: '/src/assets/blazer-navy.png' },
              ],
            },
          ],
          
          collections: [
            {
              id: 1,
              title: 'Spring Styles',
              category: 'spring',
              image: '/src/assets/shirt-linen.png',
              author: 'David Kharrat',
              styleTag: ['light', 'casual'],
              outfits: [5, 6],
              items: [
                { id: 5, title: 'Spring Stroll', preview: '/src/assets/shirt-linen.png' },
                { id: 6, title: 'Business Casual', preview: '/src/assets/blazer-navy.png' },
              ],
            },
            {
              id: 2,
              title: 'Fall Fits',
              category: 'fall',
              image: '/src/assets/turtleneck.png',
              author: 'David Kharrat',
              styleTag: ['layered', 'warm'],
              outfits: [2, 4],
              items: [
                { id: 2, title: 'Date Night', preview: '/src/assets/turtleneck.png' },
                { id: 4, title: 'Autumn Streets', preview: '/src/assets/jacket-denim.png' },
              ],
            },
            {
              id: 3,
              title: 'Lifestyle Looks',
              category: 'urban',
              image: '/src/assets/tee-graphic.png',
              author: 'David Kharrat',
              styleTag: ['minimal', 'sporty'],
              outfits: [1, 3],
              items: [
                { id: 1, title: 'Casual Friday', preview: '/src/assets/tee-graphic.png' },
                { id: 3, title: 'Gym Fit', preview: '/src/assets/joggers-navy.png' },
              ],
            },
          ],
          
          
      },
    },
  ];
  