export const wardrobes = [
    // === HATS ===
    {
      id: 1,
      category: "hat",
      itemName: "Classic Fedora",
      gender: "male",
      season: ["fall", "spring"],
      price: 45,
      temperature_range: [10, 40],
      occasion: ["formal"],
      brand: "Stetson",
      color: "brown",
      type: "fedora",
      material: "wool",
      imageUrl: "https://source.unsplash.com/200x200/?fedora",
      essential: true,
    },
    {
      id: 2,
      category: "hat",
      itemName: "Winter Beanie",
      gender: "unisex",
      season: ["winter"],
      price: 20,
      temperature_range: [-10, 10],
      occasion: ["casual"],
      brand: "North Face",
      color: "black",
      type: "beanie",
      material: "wool",
      imageUrl: "https://source.unsplash.com/200x200/?beanie",
      essential: true,
    },
    {
      id: 3,
      category: "hat",
      itemName: "Sport Cap",
      gender: "unisex",
      season: ["summer"],
      price: 18,
      temperature_range: [0, 40],
      occasion: ["sport"],
      brand: "Nike",
      color: "white",
      type: "cap",
      material: "cotton",
      imageUrl: "https://source.unsplash.com/200x200/?cap",
      essential: true,
    },
    {
      id: 4,
      category: "hat",
      itemName: "Straw Sun Hat",
      gender: "female",
      season: ["summer"],
      price: 30,
      temperature_range: [25, 40],
      occasion: ["casual"],
      brand: "Zara",
      color: "beige",
      type: "sun hat",
      material: "straw",
      imageUrl: "https://source.unsplash.com/200x200/?sunhat",
      essential: true,
    },
  
    // === SHIRTS ===
    {
      id: 5,
      category: "shirt",
      itemName: "Oxford Shirt",
      gender: "male",
      season: ["spring", "fall"],
      price: 40,
      temperature_range: [10, 22],
      occasion: ["formal"],
      brand: "Ralph Lauren",
      color: "blue",
      type: "oxford",
      material: "cotton",
      imageUrl: "https://source.unsplash.com/200x200/?oxford-shirt",
      essential: true,
    },
    {
      id: 6,
      category: "shirt",
      itemName: "Casual Polo",
      gender: "male",
      season: ["summer"],
      price: 35,
      temperature_range: [20, 35],
      occasion: ["casual"],
      brand: "Lacoste",
      color: "green",
      type: "polo",
      material: "cotton",
      imageUrl: "https://source.unsplash.com/200x200/?polo-shirt",
      essential: true,
    },
    {
      id: 7,
      category: "shirt",
      itemName: "Linen Button-Up",
      gender: "male",
      season: ["summer"],
      price: 50,
      temperature_range: [22, 35],
      occasion: ["casual"],
      brand: "H&M",
      color: "white",
      type: "button-up",
      material: "linen",
      imageUrl: "https://source.unsplash.com/200x200/?linen-shirt",
      essential: true,
    },
    {
      id: 8,
      category: "shirt",
      itemName: "Thermal Long Sleeve",
      gender: "male",
      season: ["winter"],
      price: 28,
      temperature_range: [-5, 10],
      occasion: ["casual"],
      brand: "Uniqlo",
      color: "grey",
      type: "thermal",
      material: "cotton",
      imageUrl: "https://source.unsplash.com/200x200/?thermal-shirt",
      essential: true,
    },
  
    // === JACKETS ===
    {
      id: 9,
      category: "jacket",
      itemName: "Leather Jacket",
      gender: "male",
      season: ["fall"],
      price: 120,
      temperature_range: [5, 20],
      occasion: ["casual"],
      brand: "Zara",
      color: "black",
      type: "biker",
      material: "leather",
      imageUrl: "https://source.unsplash.com/200x200/?leather-jacket",
      essential: true,
    },
    {
      id: 10,
      category: "jacket",
      itemName: "Puffer Jacket",
      gender: "unisex",
      season: ["winter"],
      price: 150,
      temperature_range: [-15, 5],
      occasion: ["casual"],
      brand: "Columbia",
      color: "navy",
      type: "puffer",
      material: "synthetic",
      imageUrl: "https://source.unsplash.com/200x200/?puffer-jacket",
      essential: true,
    },
    {
      id: 11,
      category: "jacket",
      itemName: "Blazer",
      gender: "male",
      season: ["spring", "fall"],
      price: 100,
      temperature_range: [10, 22],
      occasion: ["formal"],
      brand: "Hugo Boss",
      color: "grey",
      type: "blazer",
      material: "wool",
      imageUrl: "https://source.unsplash.com/200x200/?blazer",
      essential: true,
    },
    {
      id: 12,
      category: "jacket",
      itemName: "Raincoat",
      gender: "unisex",
      season: ["spring", "fall"],
      price: 80,
      temperature_range: [8, 18],
      occasion: ["casual"],
      brand: "Uniqlo",
      color: "yellow",
      type: "raincoat",
      material: "nylon",
      imageUrl: "https://source.unsplash.com/200x200/?raincoat",
      essential: true,
    },
  
    // === PANTS ===
    {
      id: 13,
      category: "pants",
      itemName: "Slim Fit Jeans",
      gender: "male",
      season: ["fall", "spring"],
      price: 60,
      temperature_range: [10, 25],
      occasion: ["casual"],
      brand: "Levi's",
      color: "blue",
      type: "jeans",
      material: "denim",
      imageUrl: "https://source.unsplash.com/200x200/?jeans",
      essential: true,
    },
    {
      id: 14,
      category: "pants",
      itemName: "Formal Trousers",
      gender: "male",
      season: ["spring", "fall"],
      price: 75,
      temperature_range: [10, 22],
      occasion: ["formal"],
      brand: "Calvin Klein",
      color: "black",
      type: "trousers",
      material: "wool",
      imageUrl: "https://source.unsplash.com/200x200/?trousers",
      essential: true,
    },
    {
      id: 15,
      category: "pants",
      itemName: "Shorts",
      gender: "male",
      season: ["summer"],
      price: 35,
      temperature_range: [25, 40],
      occasion: ["casual"],
      brand: "Adidas",
      color: "khaki",
      type: "shorts",
      material: "cotton",
      imageUrl: "https://source.unsplash.com/200x200/?shorts",
      essential: true,
    },
    {
      id: 16,
      category: "pants",
      itemName: "Joggers",
      gender: "unisex",
      season: ["fall", "winter"],
      price: 40,
      temperature_range: [0, 15],
      occasion: ["casual"],
      brand: "Nike",
      color: "grey",
      type: "joggers",
      material: "fleece",
      imageUrl: "https://source.unsplash.com/200x200/?joggers",
      essential: true,
    },
  
    // === SHOES ===
    {
      id: 17,
      category: "shoes",
      itemName: "Leather Oxfords",
      gender: "male",
      season: ["spring", "fall"],
      price: 95,
      temperature_range: [10, 22],
      occasion: ["formal"],
      brand: "Clarks",
      color: "brown",
      type: "oxford",
      material: "leather",
      imageUrl: "https://source.unsplash.com/200x200/?oxford-shoes",
      essential: true,
    },
    {
      id: 18,
      category: "shoes",
      itemName: "Sneakers",
      gender: "unisex",
      season: ["all"],
      price: 70,
      temperature_range: [5, 35],
      occasion: ["casual"],
      brand: "Converse",
      color: "white",
      type: "sneakers",
      material: "canvas",
      imageUrl: "https://source.unsplash.com/200x200/?sneakers",
      essential: true,
    },
    {
      id: 19,
      category: "shoes",
      itemName: "Running Shoes",
      gender: "male",
      season: ["summer"],
      price: 85,
      temperature_range: [15, 35],
      occasion: ["sport"],
      brand: "Asics",
      color: "blue",
      type: "running",
      material: "synthetic",
      imageUrl: "https://source.unsplash.com/200x200/?running-shoes",
      essential: true,
    },
    {
      id: 20,
      category: "shoes",
      itemName: "Boots",
      gender: "male",
      season: ["winter"],
      price: 120,
      temperature_range: [-10, 10],
      occasion: ["casual"],
      brand: "Timberland",
      color: "tan",
      type: "boots",
      material: "leather",
      imageUrl: "https://source.unsplash.com/200x200/?boots",
      essential: true,
    },{
      category: "hat",
      itemName: "Bucket Hat",
      gender: "female",
      season: ["spring", "summer"],
      price: 25,
      temperature_range: [10, 30],
      occasion: ["casual"],
      brand: "H&M",
      color: "yellow",
      type: "bucket",
      material: "polyester",
      imageUrl: "https://source.unsplash.com/200x200/?bucket-hat",
      essential: true
    },
    {
      category: "jacket",
      itemName: "Leather Biker Jacket",
      gender: "male",
      season: ["fall", "winter"],
      price: 120,
      temperature_range: [-5, 15],
      occasion: ["casual"],
      brand: "Zara",
      color: "black",
      type: "biker",
      material: "leather",
      imageUrl: "https://source.unsplash.com/200x200/?leather-jacket",
      essential: true
    },
    {
      category: "pants",
      itemName: "Slim Fit Jeans",
      gender: "male",
      season: ["spring", "fall"],
      price: 60,
      temperature_range: [5, 25],
      occasion: ["casual"],
      brand: "Levi's",
      color: "blue",
      type: "jeans",
      material: "denim",
      imageUrl: "https://source.unsplash.com/200x200/?jeans",
      essential: true
    },
    {
      category: "shoes",
      itemName: "Running Sneakers",
      gender: "unisex",
      season: ["spring", "summer", "fall"],
      price: 80,
      temperature_range: [10, 35],
      occasion: ["sport"],
      brand: "Nike",
      color: "white",
      type: "sneakers",
      material: "synthetic",
      imageUrl: "https://source.unsplash.com/200x200/?sneakers",
      essential: true
    },
    {
      category: "shirt",
      itemName: "Linen Button Shirt",
      gender: "male",
      season: ["summer"],
      price: 35,
      temperature_range: [20, 40],
      occasion: ["formal"],
      brand: "Uniqlo",
      color: "lightblue",
      type: "button-down",
      material: "linen",
      imageUrl: "https://source.unsplash.com/200x200/?linen-shirt",
      essential: true
    },
    {
      category: "coat",
      itemName: "Wool Overcoat",
      gender: "male",
      season: ["winter"],
      price: 150,
      temperature_range: [-10, 5],
      occasion: ["formal"],
      brand: "Topman",
      color: "gray",
      type: "overcoat",
      material: "wool",
      imageUrl: "https://source.unsplash.com/200x200/?wool-coat",
      essential: true
    },
    {
      category: "hoodie",
      itemName: "Oversized Hoodie",
      gender: "unisex",
      season: ["fall", "winter"],
      price: 45,
      temperature_range: [0, 15],
      occasion: ["casual"],
      brand: "Adidas",
      color: "red",
      type: "pullover",
      material: "fleece",
      imageUrl: "https://source.unsplash.com/200x200/?hoodie",
      essential: true
    },
    {
      category: "sweater",
      itemName: "Cable Knit Sweater",
      gender: "female",
      season: ["fall", "winter"],
      price: 55,
      temperature_range: [-5, 15],
      occasion: ["casual"],
      brand: "Gap",
      color: "cream",
      type: "knit",
      material: "wool",
      imageUrl: "https://source.unsplash.com/200x200/?sweater",
      essential: true
    },
    {
      category: "long sleeve",
      itemName: "Thermal Long Sleeve",
      gender: "male",
      season: ["winter"],
      price: 30,
      temperature_range: [-10, 10],
      occasion: ["casual"],
      brand: "Under Armour",
      color: "navy",
      type: "thermal",
      material: "cotton-blend",
      imageUrl: "https://source.unsplash.com/200x200/?thermal-shirt",
      essential: true
    },
    {
      category: "blouse",
      itemName: "Chiffon Blouse",
      gender: "female",
      season: ["spring", "summer"],
      price: 40,
      temperature_range: [15, 30],
      occasion: ["formal"],
      brand: "Mango",
      color: "white",
      type: "chiffon",
      material: "silk",
      imageUrl: "https://source.unsplash.com/200x200/?blouse",
      essential: true
    },{
      category: "accessories",
      itemName: "Silver Necklace",
      gender: "female",
      season: ["all"],
      price: 35,
      temperature_range: [0, 40],
      occasion: ["formal"],
      brand: "Pandora",
      color: "silver",
      type: "necklace",
      material: "silver",
      imageUrl: "https://source.unsplash.com/200x200/?necklace",
      essential: false
    },
    {
      category: "gloves",
      itemName: "Leather Gloves",
      gender: "unisex",
      season: ["winter"],
      price: 28,
      temperature_range: [-10, 10],
      occasion: ["formal"],
      brand: "Zegna",
      color: "brown",
      type: "gloves",
      material: "leather",
      imageUrl: "https://source.unsplash.com/200x200/?gloves",
      essential: false
    },
    {
      category: "scarf",
      itemName: "Wool Scarf",
      gender: "unisex",
      season: ["fall", "winter"],
      price: 20,
      temperature_range: [-10, 10],
      occasion: ["casual"],
      brand: "H&M",
      color: "burgundy",
      type: "scarf",
      material: "wool",
      imageUrl: "https://source.unsplash.com/200x200/?scarf",
      essential: false
    },
    {
      category: "accessories",
      itemName: "Leather Wallet",
      gender: "male",
      season: ["all"],
      price: 45,
      temperature_range: [0, 40],
      occasion: ["casual"],
      brand: "Coach",
      color: "black",
      type: "wallet",
      material: "leather",
      imageUrl: "https://source.unsplash.com/200x200/?wallet",
      essential: false
    },
    {
      category: "accessories",
      itemName: "Fashion Watch",
      gender: "female",
      season: ["all"],
      price: 65,
      temperature_range: [0, 40],
      occasion: ["formal"],
      brand: "Fossil",
      color: "gold",
      type: "watch",
      material: "metal",
      imageUrl: "https://source.unsplash.com/200x200/?watch",
      essential: false
    }
    
    
  ];
  